### ISSUE TITLE
STCNVScore bug

### ISSUE THREAD

**Issue by NiklausZZZ** [Yelab2020/Cottrazm#13]
```r
> TumorST <-
+   STCNVScore(
+     TumorST = TumorST,
+     assay = "Spatial",
+     Sample = Sample,
+     OutDir = OutDir
+   )
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file './InferCNV/output_Spatial/17_HMM_predHMMi6.rand_trees.hmm_mode-subclusters.observations_dendrogram.txt': No such file or directory
```

I have successfully run the `STCNV()`, but not generated the '17_HMM_predHMMi6.rand_trees.hmm_mode-subclusters.observations_dendrogram.txt' file. 

Any suggestions would be greatly appreciated!

**Comment by NiklausZZZ** [comment]
```R
> TumorST <-
+   STCNVScore(
+     TumorST = TumorST,
+     assay = "Spatial",
+     Sample = Sample,
+     OutDir = OutDir
+   )
Scale for fill is already present.
Adding another scale for fill, which will replace the existing scale.
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './InferCNV/output_Spatial/infercnv.17_HMM_predHMMi6.rand_trees.hmm_mode-subclusters.observations.txt': No such file or directory
```

Encountering numerous bugs despite faithfully following the tutorial.

**Comment by Lings01** [comment]
I got same error.

**Comment by elliewith** [comment]
I have also received the same error.

**Comment by Lings01** [comment]
I updated my infercnv to version 1.3.3 and solved the problem.

**Comment by Lings01** [comment]
I forked this repository and update the files[https://github.com/Lings01/Cottrazm](url)

**Comment by NiklausZZZ** [comment]
Thank you for your suggestion. It's challenging to identify the version issue without the authors' specifications.

**Comment by 7777-56** [comment]
找到脚本 用上一行那个

**Comment by Sinejune** [comment]
亲测如果使用1.3.3版本的infercnv，会导致在运行stinfercnv的过程中报错，

**Comment by Sinejune** [comment]
Strangely, when I use inferCNV v1.3.3, an error occurs midway when running STinferCNV. However, with inferCNV v1.8.1, the error does not occur, but I can't get the desired result files. In the author's source code, there is commented-out code adapted for v1.8.1. After making some simple modifications, it runs successfully.
