### ISSUE TITLE
"NA" in the results of STCNVScore

### ISSUE THREAD

**Issue by jmzhang1911** [Yelab2020/Cottrazm#2]
Hello author, I believe this tool will play an important role in my research. Thank you for developing such a useful tool. However, I have encountered some confusion after running STCNVScore. The 'cnv_score' column in the Seurat object contains mostly "NA" and a few "0". I am unsure if there is an issue with my execution and what the specific meaning of these NAs is. I am looking forward to your response.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/52552382/228120848-adb48984-d471-41f6-ad29-f20b45174445.png">

**Comment by xzz-1995** [comment]
hi, I updated the code related to STCNV and STCNVscore function that can fix the NA issues. When running the updated STCNV function, I strongly recommend using Rscript, and before the Rscript, set ulimit -s 102400 to avoid the C stack usage error.

**Comment by jmzhang1911** [comment]
Thank you for your response. I have already resolved the issue. Have a nice day!😀

**Comment by 221801007LQLXY** [comment]
Hello, I also encountered this problem, may I ask how you solve this problem
